// backend/synth/native/codes_mem.hpp
// Lookup into the compiled-in Galileo memory-code tables (galileo_e1_codes.cpp
// / galileo_e5a_codes.cpp, generated by tools/gen_galileo_e1.py /
// tools/gen_galileo_e5a.py from the Galileo OS SIS ICD Annex C primary
// codes). Internal C++ helpers -- NOT part of the extern "C" ABI.
#pragma once
#include <cstdint>

// E1-B (data) / E1-C (pilot) 4092-chip primary codes, prn 1..50 (else nullptr).
const int8_t *mem_e1b(int prn);
const int8_t *mem_e1c(int prn);
// E1-C 25-chip CS25 secondary code (Galileo OS SIS ICD).
const int8_t *cs25();

// E5a-I (data) / E5a-Q (pilot) 10230-chip primary codes, prn 1..50 (else
// nullptr). Reached via galileo_e5a_codes.hpp's gs::e5a_i / gs::e5a_q, which
// add the bounds check and buffer-fill contract every synth_code_* entry
// point shares.
const int8_t *mem_e5ai(int prn);
const int8_t *mem_e5aq(int prn);
