// backend/synth/native/codes_mem.hpp
// Lookup into the compiled-in Galileo E1 memory-code tables
// (galileo_e1_codes.cpp, generated by tools/gen_galileo_e1.py from the
// Galileo OS SIS ICD Annex C.7/C.8 primary codes). Internal C++ helpers --
// NOT part of the extern "C" ABI.
#pragma once
#include <cstdint>

// E1-B (data) / E1-C (pilot) 4092-chip primary codes, prn 1..50 (else nullptr).
const int8_t *mem_e1b(int prn);
const int8_t *mem_e1c(int prn);
// E1-C 25-chip CS25 secondary code (Galileo OS SIS ICD).
const int8_t *cs25();
