"""Generate backend/synth/native/galileo_e1_codes.cpp from the Galileo OS
SIS ICD E1 primary memory-code hex table (tools/galileo_e1_icd_codes.txt).

Galileo E1-B (data) and E1-C (pilot) are NOT LFSR-generated: they are fixed
4092-chip memory codes published in the Galileo OS SIS ICD (Annex C.7 / C.8),
PRN 1..50. The committed hex table is transcribed from GNSS-SDR
src/core/system_parameters/Galileo_E1.h (arrays GALILEO_E1_B_PRIMARY_CODE /
GALILEO_E1_C_PRIMARY_CODE). The E1-C 25-chip CS25 secondary is the ICD
GALILEO_E1_C_SECONDARY_CODE "0011100000001010110110010".

Run once; the emitted .cpp is committed.

    python tools/gen_galileo_e1.py tools/galileo_e1_icd_codes.txt \
        backend/synth/native/galileo_e1_codes.cpp

Bit -> chip mapping is the SAME convention as the GPS/BeiDou path in
ca_code.cpp: hex/bit 1 -> -1, bit 0 -> +1 (do NOT invert).
"""
import sys

PRIM_LEN = 4092
N_PRN = 50

# ICD GALILEO_E1_C_SECONDARY_CODE, bit string, mapped 1 -> -1 / 0 -> +1.
CS25_BITS = "0011100000001010110110010"


def bits_from_hex(h: str, n: int) -> list[int]:
    if len(h) * 4 != n:
        raise ValueError(f"expected {n // 4} hex chars, got {len(h)}")
    v = int(h, 16)
    return [-1 if (v >> (n - 1 - i)) & 1 else 1 for i in range(n)]  # MSB first


def bits_from_str(s: str) -> list[int]:
    return [-1 if c == "1" else 1 for c in s]


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    e1b: dict[int, list[int]] = {}
    e1c: dict[int, list[int]] = {}
    with open(src) as fh:
        for ln in fh:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            tag, prn, hexs = ln.split()
            (e1b if tag == "E1B" else e1c)[int(prn)] = bits_from_hex(hexs, PRIM_LEN)
    for name, tbl in (("E1B", e1b), ("E1C", e1c)):
        missing = [p for p in range(1, N_PRN + 1) if p not in tbl]
        if missing:
            raise SystemExit(f"{name}: missing PRN(s) {missing}")

    cs25 = bits_from_str(CS25_BITS)
    if len(cs25) != 25:
        raise SystemExit("CS25 must be 25 chips")

    with open(dst, "w") as f:
        f.write("// GENERATED by tools/gen_galileo_e1.py -- DO NOT EDIT.\n")
        f.write("// Source: tools/galileo_e1_icd_codes.txt (Galileo OS SIS ICD E1\n")
        f.write("// memory codes, transcribed from GNSS-SDR Galileo_E1.h).\n")
        f.write('#include "codes_mem.hpp"\n#include <cstdint>\n\n')
        for name, tbl in (("kE1B", e1b), ("kE1C", e1c)):
            f.write(f"extern const int8_t {name}[{N_PRN}][{PRIM_LEN}] = {{\n")
            for prn in range(1, N_PRN + 1):
                row = tbl[prn]
                f.write("  {" + ",".join(str(x) for x in row) + "},\n")
            f.write("};\n\n")
        f.write("extern const int8_t kCS25[25] = {"
                + ",".join(str(x) for x in cs25) + "};\n")


if __name__ == "__main__":
    main()
