"""Generate backend/synth/native/galileo_e5a_codes.cpp from the Galileo OS
SIS ICD E5a primary memory-code hex table (tools/galileo_e5a_icd_codes.txt).

Galileo E5a-I (data) and E5a-Q (pilot) are NOT LFSR-generated: they are fixed
10230-chip memory codes published in the Galileo OS SIS ICD Annex C. The
committed hex table is transcribed from GNSS-SDR
src/core/system_parameters/Galileo_E5a.h (arrays GALILEO_E5A_I_PRIMARY_CODE /
GALILEO_E5A_Q_PRIMARY_CODE), same source family as tools/gen_galileo_e1.py.

Each source row is 2558 hex chars = 10232 bits (GNSS-SDR's own
hex_to_binary_converter / galileo_e5_a_code_gen_complex_primary expands every
hex digit to 4 bits and then only consumes the first 10230 of them -- the
last hex digit's low 2 bits are unused padding). This script reproduces that
exact truncation.

Run once; the emitted .cpp is committed.

    python tools/gen_galileo_e5a.py tools/galileo_e5a_icd_codes.txt \
        backend/synth/native/galileo_e5a_codes.cpp

Bit -> chip mapping is the SAME convention as the GPS/BeiDou/Galileo-E1 path
in ca_code.cpp: hex/bit 1 -> -1, bit 0 -> +1 (do NOT invert), MSB first.
"""
import sys

PRIM_LEN = 10230
HEX_CHARS = 2558   # 2558*4 = 10232 raw bits; keep only the first 10230
N_PRN = 50


def bits_from_hex_truncated(h: str) -> list[int]:
    if len(h) != HEX_CHARS:
        raise ValueError(f"expected {HEX_CHARS} hex chars, got {len(h)}")
    v = int(h, 16)
    n = HEX_CHARS * 4
    bits = [-1 if (v >> (n - 1 - i)) & 1 else 1 for i in range(n)]  # MSB first
    return bits[:PRIM_LEN]


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    e5ai: dict[int, list[int]] = {}
    e5aq: dict[int, list[int]] = {}
    with open(src) as fh:
        for ln in fh:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            tag, prn, hexs = ln.split()
            (e5ai if tag == "E5AI" else e5aq)[int(prn)] = bits_from_hex_truncated(hexs)
    for name, tbl in (("E5AI", e5ai), ("E5AQ", e5aq)):
        missing = [p for p in range(1, N_PRN + 1) if p not in tbl]
        if missing:
            raise SystemExit(f"{name}: missing PRN(s) {missing}")
        for p, row in tbl.items():
            if len(row) != PRIM_LEN:
                raise SystemExit(f"{name} PRN {p}: length {len(row)} != {PRIM_LEN}")

    with open(dst, "w") as f:
        f.write("// GENERATED by tools/gen_galileo_e5a.py -- DO NOT EDIT.\n")
        f.write("// Source: tools/galileo_e5a_icd_codes.txt (Galileo OS SIS ICD E5a\n")
        f.write("// memory codes, transcribed from GNSS-SDR Galileo_E5a.h).\n")
        f.write('#include "codes_mem.hpp"\n#include <cstdint>\n\n')
        for name, tbl in (("kE5AI", e5ai), ("kE5AQ", e5aq)):
            f.write(f"extern const int8_t {name}[{N_PRN}][{PRIM_LEN}] = {{\n")
            for prn in range(1, N_PRN + 1):
                row = tbl[prn]
                f.write("  {" + ",".join(str(x) for x in row) + "},\n")
            f.write("};\n\n")


if __name__ == "__main__":
    main()
